### ISSUE TITLE
Feature Request to my future me: Add coercing for data types

### ISSUE THREAD

**Issue by Ygor-J** [Ygor-J/sql-guard#3]
Say I want to have regex-like validation for an integer field, I would not be able to do that.

So first, I'd have to SAFE CAST the integer field to a string and then apply regex rules.

Example in a YAML file in pandera:
```
  component_position:
    dtype: str
    nullable: false
    checks:
      str_matches: ^(?:[1-9]|[12]\d|30)$ # Regex for numeric 1-30
    required: true
    coerce: true
```
